site_name: "Nutanix on Equinix Metal"

repo_url: https://github.com/equinix-labs/nutanix-on-equinix-metal-workshop
repo_name: equinix-labs/nutanix-on-equinix-metal-workshop
edit_uri: blob/main/docs

extra_css:
  - stylesheets/extra.css

nav:
  - Introduction: index.md

  - Parts:
      - 1. Setup: parts/1-setup.md
      - 2. Provision a Nutanix cluster: parts/2-provision_nutanix_cluster.md
      - 3. Access the Prism UI: parts/3-access_prism_ui.md
      - 4. Create a VM: parts/4-create_a_vm.md
      - 5. Prism Central: parts/5-prism_central.md
      - 6. Kubernetes: parts/6-kubernetes.md
      - Conclusion: parts/conclusion.md

theme:
  name: material
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: custom
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: custom
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  icon:
    logo: simple/equinixmetal
  favicon: images/favicon.ico

  features:
    - navigation.top
    - search.highlight
    - navigation.footer
    - content.code.copy
    - navigation.expand

extra:
  social:
    - icon: simple/equinixmetal
      link: https://deploy.equinix.com
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/@equinixmetal
    - icon: fontawesome/brands/github
      link: https://github.com/equinix-labs
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/@EquinixDevelopers

plugins:
  - search
  - glightbox

markdown_extensions:
  - admonition
  - pymdownx.details
  - toc:
      permalink: true
  - tables
  - pymdownx.betterem
  - pymdownx.critic
  - pymdownx.highlight:
      anchor_linenums: true
      auto_title: true
  - pymdownx.superfences
  - pymdownx.keys
